export const ACTIVE_NAV = 'ACTIVE_NAV'
export const CURRENT_ANIMATE = 'CURRENT_ANIMATE'
export const RECEIVE_NAV = 'RECEIVE_NAV'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const SAVE_ARTICLES_LIST = 'SAVE_ARTICLES_LIST'